import React, { useState } from "react";
import { PromptPackage } from "@/types";
import { PLATFORM_PROFILES } from "@/config/platforms";
import { Copy, Check, Download, Edit3, Sparkles, Archive, RefreshCw } from "lucide-react";

interface FinalPromptCardProps {
  promptPackage: PromptPackage;
  onRefineAgain?: (correctionText: string) => void;
  isRefiningAgain?: boolean;
}

export const FinalPromptCard: React.FC<FinalPromptCardProps> = ({
  promptPackage,
  onRefineAgain,
  isRefiningAgain,
}) => {
  const [copiedPrompt, setCopiedPrompt] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editedPrompt, setEditedPrompt] = useState(promptPackage.finalPrompt);
  const [showRefineInput, setShowRefineInput] = useState(false);
  const [correctionText, setCorrectionText] = useState("");

  const platformProfile = PLATFORM_PROFILES[promptPackage.platform];

  const handleCopyPrompt = () => {
    navigator.clipboard.writeText(editedPrompt);
    setCopiedPrompt(true);
    setTimeout(() => setCopiedPrompt(false), 2000);
  };

  const handleExportTxt = () => {
    const textContent = `=== OPTIMIZED PROMPT FOR ${promptPackage.platform.toUpperCase()} ===
Generated by Job Vacancy Prompt Builder (Hermes V2)
Date: ${new Date(promptPackage.createdAt).toLocaleString()}
Aspect Ratio: ${promptPackage.aspectRatio}

[FINAL PROMPT]
${editedPrompt}

${
  promptPackage.referenceGuide && promptPackage.referenceGuide.length > 0
    ? `[REFERENCE UPLOAD GUIDE]
${promptPackage.referenceGuide
  .map(
    (item, idx) =>
      `${idx + 1}. ${item.referenceId} (${item.role.toUpperCase()})\n   Instruction: ${item.instruction}`
  )
  .join("\n\n")}`
    : ""
}

${
  promptPackage.assumptions.length > 0
    ? `[ASSUMPTIONS]
- ${promptPackage.assumptions.join("\n- ")}`
    : ""
}
`;

    const blob = new Blob([textContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `job-vacancy-prompt-${promptPackage.platform}-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleRefineSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!correctionText.trim() || !onRefineAgain) return;
    onRefineAgain(correctionText);
    setCorrectionText("");
    setShowRefineInput(false);
  };

  return (
    <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-5 shadow-xl space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between pb-3 border-b border-slate-800">
        <div>
          <div className="flex items-center space-x-2">
            <span className="inline-block w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse" />
            <h3 className="text-base font-bold text-slate-100">
              Prompt Ready for {platformProfile?.label || promptPackage.platform.toUpperCase()}
            </h3>
          </div>
          <p className="text-xs text-slate-400 mt-0.5">
            Self-contained prompt optimized for paste into {platformProfile?.label}
          </p>
        </div>

        <span className="text-xs font-mono px-2.5 py-1 rounded-lg bg-slate-950 border border-slate-800 text-amber-400 font-bold">
          {promptPackage.aspectRatio}
        </span>
      </div>

      {/* Main Text Card / Textarea */}
      <div className="relative group">
        {isEditing ? (
          <textarea
            rows={10}
            value={editedPrompt}
            onChange={(e) => setEditedPrompt(e.target.value)}
            className="w-full p-4 bg-slate-950/90 border border-amber-500/60 rounded-xl text-sm font-mono text-slate-100 focus:outline-none leading-relaxed resize-none shadow-inner"
          />
        ) : (
          <div className="w-full max-h-[350px] overflow-y-auto p-4 bg-slate-950/80 border border-slate-800 rounded-xl text-sm font-mono text-slate-200 leading-relaxed whitespace-pre-wrap select-all">
            {editedPrompt}
          </div>
        )}
      </div>

      {/* Action Buttons */}
      <div className="flex flex-wrap gap-2 pt-1">
        <button
          type="button"
          onClick={handleCopyPrompt}
          className="flex-1 py-2.5 px-4 rounded-xl font-semibold text-xs bg-amber-500 text-slate-950 hover:bg-amber-400 active:scale-[0.98] transition-all flex items-center justify-center space-x-2 shadow-md shadow-amber-500/10"
        >
          {copiedPrompt ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
          <span>{copiedPrompt ? "Copied to Clipboard!" : "Copy Prompt"}</span>
        </button>

        <button
          type="button"
          onClick={() => setIsEditing(!isEditing)}
          className="py-2.5 px-3.5 rounded-xl font-semibold text-xs bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 flex items-center justify-center space-x-1.5 transition-all"
        >
          <Edit3 className="w-4 h-4 text-slate-400" />
          <span>{isEditing ? "Done Editing" : "Edit Prompt"}</span>
        </button>

        <button
          type="button"
          onClick={handleExportTxt}
          className="py-2.5 px-3.5 rounded-xl font-semibold text-xs bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 flex items-center justify-center space-x-1.5 transition-all"
          title="Export as .txt"
        >
          <Download className="w-4 h-4 text-slate-400" />
          <span>Export TXT</span>
        </button>

        {onRefineAgain && (
          <button
            type="button"
            onClick={() => setShowRefineInput(!showRefineInput)}
            className="py-2.5 px-3.5 rounded-xl font-semibold text-xs bg-purple-500/10 hover:bg-purple-500/20 text-purple-300 border border-purple-500/30 flex items-center justify-center space-x-1.5 transition-all"
          >
            <RefreshCw className="w-4 h-4 text-purple-400" />
            <span>Refine Again</span>
          </button>
        )}
      </div>

      {/* Single-step follow-up correction input */}
      {showRefineInput && onRefineAgain && (
        <form onSubmit={handleRefineSubmit} className="pt-2 space-y-2 border-t border-slate-800">
          <label className="block text-xs font-semibold text-purple-300">
            Tell Hermes how to refine this prompt:
          </label>
          <div className="flex gap-2">
            <input
              type="text"
              value={correctionText}
              onChange={(e) => setCorrectionText(e.target.value)}
              placeholder="e.g. Make the background less busy and move model to the right..."
              className="flex-1 px-3 py-2 bg-slate-950 border border-purple-500/40 rounded-xl text-xs text-slate-100 placeholder:text-slate-600 focus:outline-none"
            />
            <button
              type="submit"
              disabled={isRefiningAgain || !correctionText.trim()}
              className="px-4 py-2 bg-purple-600 hover:bg-purple-500 text-white font-semibold text-xs rounded-xl disabled:opacity-50 transition-colors"
            >
              {isRefiningAgain ? "Refining..." : "Send"}
            </button>
          </div>
        </form>
      )}
    </div>
  );
};
